# Big Query

In [1]:
# Importamos
from google.cloud import bigquery

In [2]:
from google.oauth2 import service_account

In [3]:
import pandas as pd

In [4]:
# DB
from sqlalchemy import create_engine

# Data analysis and wrangling
import numpy as np
import random as rnd

# Visualization
import seaborn as sns
from scipy.stats import norm, skew
from scipy import stats
import matplotlib.pyplot as plt
%matplotlib inline

# Warnings and other tools
import itertools
import warnings
warnings.filterwarnings("ignore")

In [5]:
!ls ~/.creds

trim-heaven-301811-7b40bce8b0f8.json

In [6]:
# creamos las variables de entorno
creds = service_account.Credentials.from_service_account_file("/Users/victoriasofia93/.creds/trim-heaven-301811-7b40bce8b0f8.json")

In [7]:
proj_id = "trim-heaven-301811"

In [8]:
# Llamamos la funciÃ³n Client
client = bigquery.Client(project=proj_id, credentials=creds)

In [15]:
# Testing
query = (
    'SELECT * FROM `bigquery-public-data.samples.natality` '
    'LIMIT 50'
        )

In [49]:
query_nacimientos = ("""
SELECT 
    state AS estado,
    SUM(CASE WHEN year >= 1970 AND year < 1980 THEN plurality ELSE 0 END) AS B70,
    SUM(CASE WHEN year >= 1980 AND year < 1990 THEN plurality ELSE 0 END) AS B80,
    SUM(CASE WHEN year >= 1990 AND year < 2000 THEN plurality ELSE 0 END) AS B90,
    SUM(CASE WHEN year >= 2000 AND year <=2010 THEN plurality  ELSE 0 END ) AS B00,
    SUM(IF(is_male = TRUE, 1, 0)) AS Male,
    SUM(IF(is_male = FALSE, 1, 0)) AS Female,
    ROUND(AVG(weight_pounds * 0.453592),3) AS Weight
    

FROM `bigquery-public-data.samples.natality`
WHERE 
    NOT IS_NAN(plurality) AND plurality >1 AND state is NOT NULL 
GROUP BY 
    1
ORDER BY 
    1

""")

In [50]:
query_job_nacimientos = client.query(query_nacimientos)

In [51]:
query_job_nacimientos.state

'RUNNING'

In [80]:
df_nacimientos = query_job_nacimientos.to_dataframe()
df_nacimientos

   estado    B70     B80     B90     B00    Male  Female  Weight
0      AK   1529    4529    4971    2714    3391    3396   2.464
1      AL  14866   26254   33540   21033   23479   23407   2.277
2      AR   5703   14453   16504   10678   11598   11751   2.318
3      AZ   6523   17201   36109   25765   20775   20761   2.346
4      CA  56624  147762  274371  159740  156282  157163   2.405
5      CO  12704   23079   32601   22479   22324   22024   2.292
6      CT   6887   19684   30100   18537   18463   18173   2.384
7      DC   4105    7863   12071    6088    7373    7232   2.258
8      DE   1517    3398    7047    4769    4082    4052   2.302
9      FL  35721   67570  101555   65804   66529   66131   2.324
10     GA  14105   31195   62185   44634   37509   37113   2.298
11     HI   2728    6861    8141    5025    5438    5708   2.357
12     IA  12318   16850   20552   12578   15456   15080   2.432
13     ID   3353    6754    7617    6116    5871    5893   2.439
14     IL  54274   82399  109431   67318   76938   75949   2.350
15     IN  17700   35039   45554   29408   31038   31229   2.363
16     KS   9439   15872   18728   12359   13966   13746   2.366
17     KY  14359   21149   25976   17372   19535   19192   2.344
18     LA  21035   35766   37086   21762   28713   28151   2.265
19     MA  16547   36487   58530   39061   36887   36410   2.408
20     MD  12803   26584   40107   27492   26122   26119   2.339
21     ME   4506    6193    8076    4632    5784    5740   2.435
22     MI  44665   62224   81500   47664   58288   57173   2.346
23     MN  14967   28263   37706   25120   25919   25775   2.424
24     MO  25039   34825   45850   28357   32753   32995   2.322
25     MS   9387   19577   21223   13200   15730   15554   2.281
26     MT   3678    5196    5052    3493    4328    4267   2.428
27     NC  22560   39162   58243   40127   39352   39175   2.284
28     ND   1821    4373    5784    3242    3776    3625   2.397
29     NE   7277   12034   15101    9573   10710   10614   2.361
30     NH   3699    6174    7534    4925    5614    5366   2.487
31     NJ  18583   43139   73119   48455   44384   44599   2.365
32     NM   2880    7833   11259    6312    6972    6992   2.357
33     NV   2598    6386   12585    9980    7707    7748   2.306
34     NY  69364  117076  167542   99497  111583  109968   2.371
35     OH  38654   71705   92355   55657   63514   62471   2.358
36     OK  11305   21504   22225   13831   17085   16823   2.356
37     OR  10466   18117   23200   14763   16373   16312   2.441
38     PA  28736   71515   90686   51544   59655   58848   2.355
39     RI   4148    5959    9093    6028    6181    6120   2.356
40     SC  14136   21814   27763   17073   20091   19669   2.292
41     SD   1897    5042    6175    3930    4181    4185   2.396
42     TN  18556   31035   43236   28085   29623   29762   2.260
43     TX  58549  124826  160076  109302  111357  110908   2.334
44     UT   7307   16772   20597   14146   14676   14126   2.371
45     VA  18236   35158   49755   33618   33623   33630   2.341
46     VT   2081    3163    3612    1958    2729    2612   2.381
47     WA  11431   29364   37868   23735   25193   25165   2.455
48     WI  18640   31430   36660   21630   26705   26456   2.425
49     WV   6873   10023   10711    6245    8479    8203   2.323
50     WY   1306    3064    2412    1296    1979    2040   2.465

In [16]:
query

'SELECT * FROM `bigquery-public-data.samples.natality` LIMIT 50'

In [17]:
query_job = client.query(query)

In [18]:
# para visualizar el estado de ejecuciÃ³n: query_job.state
query_job.state

'RUNNING'

In [19]:
rows = query_job.result()
for row in rows:
    print(row)

Row((2005, 2005, 7, None, 3, None, False, None, 8.62889293468, 1, None, 9, None, 78, 34, 41, '09262004', True, None, False, None, False, None, 57, 9, 0, 0, 10, 78, 38, 1), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((2005, 2005, 4, None, 6, None, True, None, 2.6786164833, 1, None, 6, None, 78, 36, 34, '09012004', True, None, False, None, False, None, 23, 7, 0, 0, 8, 78, 39, 1), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((2006, 2006, 5, None, 1, None, True, None, 11.06279630716, 1, None, 9, None, 68, 38, 41, '08082005', True, None, False, None, False, None, 11, None, None, None, 8, 68, 41, 1), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((2007, 2007, 3, None, 2, None, False, None, 5.43659938092, 2, None, 9, None, 78, 42, 38, '99999999', True, None, False, None, False, None, 10, None, None, None, 8, 78, 42, 1), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((2007, 2007, 4, None, 7, None, False, None, 3.5604655312999998, 1, None, 8, None, 78, 38, 31, '09022006', True, None, False, None, False, None, 18, None, None, None, 8, 78, 43, 1), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((2007, 2007, 4, None, 1, None, True, None, 5.99877814902, 1, None, 9, None, 78, 37, 39, '07072006', True, None, False, None, False, None, 20, None, None, None, 8, 78, 42, 1), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((2008, 2008, 1, None, 4, None, True, None, 9.18666245754, 1, None, 8, None, 78, 28, 38, '04072007', False, None, True, 5, True, None, 37, None, None, None, 8, 78, 36, 1), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((1998, 1998, 1, None, 7, 'AK', False, 9, 4.87442061282, 1, 99, 9, 'AK', 3, 26, 36, '05021997', True, 'AK', None, None, True, 99, 17, 5, 2, 1, 8, 7, 27, 1), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((2003, 2003, 12, None, 6, 'AR', False, None, 8.000575487979999, 1, None, 9, 'AR', 78, 36, 40, '99999999', True, 'YY', False, None, False, None, 13, 10, 0, 0, 11, 78, 39, 1), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((1969, 1969, 6, 23, None, 'CA', True, 7, 7.43839671988, None, None, None, 'CA', 7, 45, 38, '09301998', None, '', None, None, None, None, None, 8, 1, 2, 12, 7, 47, 2), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((1971, 1971, 5, 18, None, 'CA', True, 4, 10.56234697242, 1, None, None, 'CA', 4, 29, 99, '9999191-', None, 'Foreign', None, None, None, None, None, 7, 0, 0, 8, 4, 39, 2), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((1974, 1974, 6, 30, None, 'CA', False, 7, 4.43790533406, 1, None, None, 'CA', 1, 36, 37, '10131943', None, 'CA', None, None, None, None, None, 7, 55, 55, 8, 7, 30, 2), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((1981, 1981, 11, 11, None, 'CA', True, 4, 6.7902376696, 2, 99, 99, 'CA', 7, 38, 41, '01241911', True, 'Foreign', None, None, None, None, None, 7, 0, 1, 9, 4, 41, 2), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((1981, 1981, 2, 24, None, 'CA', True, 5, 8.96840481816, 1, 99, 99, 'CA', 1, 32, 99, '9999191-', False, 'CA', None, None, None, None, None, 7, 0, 0, 8, 5, 26, 2), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((1984, 1984, 12, 13, None, 'CA', True, 7, 6.75055446244, 1, 99, 99, 'CA', 7, 41, 37, '03251944', True, 'Foreign', None, None, None, None, None, 5, 0, 2, 8, 7, 45, 2), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((1988, 1988, 5, 18, None, 'CA', True, 7, 8.1350574678, 1, 99, 99, 'CA', 7, 34, 37, '08291987', True, 'Foreign', None, None, None, None, None, 7, 0, 0, 8, 7, 37, 1), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((1989, 1989, 9, None, 6, 'CA', False, 7, 6.5256829552, 1, 99, 99, 'CA', 7, 33, 39, '12101988', True, 'Foreign', None, None, None, None, 99, 6, 1, 1, 8, 7, 34, 1), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((1995, 1995, 9, None, 4, 'CA', True, 9, 6.5697754076, 1, 99, 99, 'CA', 7, 39, 37, '12151994', True, 'Foreign', None, None, None, None, 99, 7, 1, 0, 9, 7, 37, 1), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((1995, 1995, 10, None, 5, 'CA', False, 9, 7.6610636045, 1, 99, 99, 'CA', 38, 25, 41, '12161994', True, 'Foreign', None, None, None, None, 99, 7, 0, 0, 8, 38, 31, 1), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((1995, 1995, 10, None, 4, 'CA', True, 9, 5.43659938092, 2, 99, 99, 'CA', 1, 29, 33, '02101995', False, 'CA', None, None, None, None, 99, 7, 0, 0, 8, 4, 35, 1), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((1995, 1995, 11, None, 7, 'CA', True, 9, 8.50102482272, 1, 99, 99, 'CA', 7, 40, 40, '02181995', True, 'Foreign', None, None, None, None, 99, 9, 0, 0, 10, 7, 61, 1), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((2003, 2003, 3, None, 6, 'CA', True, None, 7.13415879832, 1, None, None, 'CA', 68, 43, 37, '07012002', True, 'YY', None, None, None, None, 99, 9, 0, 0, 10, 68, 42, 1), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((2003, 2003, 10, None, 5, 'CA', True, None, 8.421658408399999, 1, None, None, 'CA', 68, 34, 43, '12992002', True, 'YY', None, None, None, None, 99, 8, 0, 0, 9, 68, 39, 1), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((2004, 2004, 11, None, 1, 'CA', False, None, 8.68841774542, 1, None, None, 'CA', 68, 34, None, '99999999', True, 'YY', None, None, None, None, 99, 11, 0, 0, 12, 68, 31, 1), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((2004, 2004, 3, None, 4, 'CO', True, None, 8.375361333379999, 1, None, 9, 'CO', 78, 39, 39, '06122003', True, 'MX', False, None, False, None, 69, 9, 0, 0, 10, 78, 40, 1), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})
Row((1993, 1993, 11, None, 7, 'DC', False, 4, 8.375361333379999, 1, 8, 9, 'DC', 4, 38, 36, '03151993', True, 'Foreign', None, None, False, None, None, 7, 0, 0, 8, 4, 49, 1), {'source_year': 0, 'year': 1, 'month': 2, 'day': 3, 'wday': 4, 'state': 5, 'is_male': 6, 'child_race': 7, 'weight_pounds': 8, 'plurality': 9, 'apgar_1min': 10, 'apgar_5min': 11, 'mother_residence_state': 12, 'mother_race': 13, 'mother_age': 14, 'gestation_weeks': 15, 'lmp': 16, 'mother_married': 17, 'mother_birth_state': 18, 'cigarette_use': 19, 'cigarettes_per_day': 20, 'alcohol_use': 21, 'drinks_per_week': 22, 'weight_gain_pounds': 23, 'born_alive_alive': 24, 'born_alive_dead': 25, 'born_dead': 26, 'ever_born': 27, 'father_race': 28, 'father_age': 29, 'record_weight': 30})

In [20]:
# Convertimos los datos de filas a dataframe
df = query_job.to_dataframe()
df

,source_year,year,month,day,wday,state,is_male,child_race,weight_pounds,plurality,...,alcohol_use,drinks_per_week,weight_gain_pounds,born_alive_alive,born_alive_dead,born_dead,ever_born,father_race,father_age,record_weight
0,2005,2005,7,NaN,3.0,None,False,NaN,8.628893,1.0,...,False,NaN,57.0,9.0,0.0,0.0,10,78,38,1
1,2005,2005,4,NaN,6.0,None,True,NaN,2.678616,1.0,...,False,NaN,23.0,7.0,0.0,0.0,8,78,39,1
2,2006,2006,5,NaN,1.0,None,True,NaN,11.062796,1.0,...,False,NaN,11.0,NaN,NaN,NaN,8,68,41,1
3,2007,2007,3,NaN,2.0,None,False,NaN,5.436599,2.0,...,False,NaN,10.0,NaN,NaN,NaN,8,78,42,1
4,2007,2007,4,NaN,7.0,None,False,NaN,3.560466,1.0,...,False,NaN,18.0,NaN,NaN,NaN,8,78,43,1
5,2007,2007,4,NaN,1.0,None,True,NaN,5.998778,1.0,...,False,NaN,20.0,NaN,NaN,NaN,8,78,42,1
6,2008,2008,1,NaN,4.0,None,True,NaN,9.186662,1.0,...,True,NaN,37.0,NaN,NaN,NaN,8,78,36,1
7,1998,1998,1,NaN,7.0,AK,False,9.0,4.874421,1.0,...,True,99.0,17.0,5.0,2.0,1.0,8,7,27,1
8,2003,2003,12,NaN,6.0,AR,False,NaN,8.000575,1.0,...,False,NaN,13.0,10.0,0.0,0.0,11,78,39,1
9,1969,1969,6,23.0,NaN,CA,True,7.0,7.438397,NaN,...,None,NaN,NaN,8.0,1.0,2.0,12,7,47,2
10,1971,1971,5,18.0,NaN,CA,True,4.0,10.562347,1.0,...,None,NaN,NaN,7.0,0.0,0.0,8,4,39,2
11,1974,1974,6,30.0,NaN,CA,False,7.0,4.437905,1.0,...,None,NaN,NaN,7.0,55.0,55.0,8,7,30,2
12,1981,1981,11,11.0,NaN,CA,True,4.0,6.790238,2.0,...,None,NaN,NaN,7.0,0.0,1.0,9,4,41,2
13,1981,1981,2,24.0,NaN,CA,True,5.0,8.968405,1.0,...,None,NaN,NaN,7.0,0.0,0.0,8,5,26,2
14,1984,1984,12,13.0,NaN,CA,True,7.0,6.750554,1.0,...,None,NaN,NaN,5.0,0.0,2.0,8,7,45,2
15,1988,1988,5,18.0,NaN,CA,True,7.0,8.135057,1.0,...,None,NaN,NaN,7.0,0.0,0.0,8,7,37,1
16,1989,1989,9,NaN,6.0,CA,False,7.0,6.525683,1.0,...,None,NaN,99.0,6.0,1.0,1.0,8,7,34,1
17,1995,1995,9,NaN,4.0,CA,True,9.0,6.569775,1.0,...,None,NaN,99.0,7.0,1.0,0.0,9,7,37,1
18,1995,1995,10,NaN,5.0,CA,False,9.0,7.661064,1.0,...,None,NaN,99.0,7.0,0.0,0.0,8,38,31,1
19,1995,1995,10,NaN,4.0,CA,True,9.0,5.436599,2.0,...,None,NaN,99.0,7.0,0.0,0.0,8,4,35,1
20,1995,1995,11,NaN,7.0,CA,True,9.0,8.501025,1.0,...,None,NaN,99.0,9.0,0.0,0.0,10,7,61,1
21,2003,2003,3,NaN,6.0,CA,True,NaN,7.134159,1.0,...,None,NaN,99.0,9.0,0.0,0.0,10,68,42,1
22,2003,2003,10,NaN,5.0,CA,True,NaN,8.421658,1.0,...,None,NaN,99.0,8.0,0.0,0.0,9,68,39,1
23,2004,2004,11,NaN,1.0,CA,False,NaN,8.688418,1.0,...,None,NaN,99.0,11.0,0.0,0.0,12,68,31,1
24,2004,2004,3,NaN,4.0,CO,True,NaN,8.375361,1.0,...,False,NaN,69.0,9.0,0.0,0.0,10,78,40,1
25,1993,1993,11,NaN,7.0,DC,False,4.0,8.375361,1.0,...,False,NaN,NaN,7.0,0.0,0.0,8,4,49,1
26,1969,1969,2,25.0,NaN,HI,False,6.0,5.500533,NaN,...,None,NaN,NaN,10.0,2.0,0.0,13,6,38,2
27,1969,1969,3,30.0,NaN,HI,True,6.0,7.187070,NaN,...,None,NaN,NaN,7.0,0.0,0.0,8,7,27,2
28,1971,1971,12,16.0,NaN,HI,True,6.0,7.187070,1.0,...,None,NaN,NaN,9.0,0.0,0.0,10,7,39,2
29,1971,1971,9,30.0,NaN,HI,False,6.0,6.375769,1.0,...,None,NaN,NaN,4.0,3.0,0.0,8,6,28,2
30,1971,1971,4,8.0,NaN,HI,False,7.0,7.500126,1.0,...,None,NaN,NaN,11.0,0.0,1.0,13,7,37,2
31,1978,1978,1,16.0,NaN,HI,False,6.0,7.187070,1.0,...,None,NaN,NaN,6.0,1.0,1.0,9,6,31,2
32,1983,1983,6,15.0,NaN,HI,True,6.0,6.750554,1.0,...,None,NaN,NaN,5.0,0.0,3.0,9,6,30,1
33,1984,1984,7,22.0,NaN,HI,False,6.0,8.113011,1.0,...,None,NaN,NaN,5.0,0.0,3.0,9,5,25,1
34,1984,1984,9,11.0,NaN,HI,False,7.0,7.187070,1.0,...,None,NaN,NaN,3.0,0.0,4.0,8,7,24,1
35,1986,1986,6,27.0,NaN,HI,True,5.0,4.607661,1.0,...,None,NaN,NaN,2.0,0.0,5.0,8,5,29,1
36,1986,1986,2,4.0,NaN,HI,False,7.0,8.090965,1.0,...,None,NaN,NaN,7.0,1.0,0.0,9,7,52,1
37,1987,1987,6,23.0,NaN,HI,True,6.0,7.363440,1.0,...,None,NaN,NaN,14.0,0.0,0.0,15,6,46,1
38,1988,1988,7,25.0,NaN,HI,False,6.0,6.124442,1.0,...,None,NaN,NaN,6.0,0.0,1.0,8,6,26,1
39,1988,1988,8,5.0,NaN,HI,True,7.0,9.023520,1.0,...,None,NaN,NaN,2.0,0.0,5.0,8,7,39,1
40,1998,1998,9,NaN,7.0,HI,True,9.0,10.200789,1.0,...,False,NaN,99.0,7.0,0.0,0.0,8,6,40,1
41,1998,1998,11,NaN,6.0,IL,False,9.0,4.874421,2.0,...,False,NaN,45.0,7.0,0.0,0.0,8,48,34,1
42,2002,2002,11,NaN,3.0,IL,True,9.0,5.000084,2.0,...,False,NaN,32.0,7.0,0.0,0.0,8,18,39,1
43,1988,1988,5,29.0,NaN,LA,True,4.0,8.126239,1.0,...,None,NaN,NaN,1.0,0.0,6.0,8,4,23,1
44,2003,2003,5,NaN,6.0,OR,True,NaN,8.811877,1.0,...,False,NaN,18.0,8.0,0.0,0.0,9,78,99,1
45,1999,1999,1,NaN,4.0,TX,True,9.0,8.249698,1.0,...,False,NaN,16.0,8.0,2.0,0.0,11,38,39,1
46,2001,2001,7,NaN,4.0,TX,True,9.0,6.812284,1.0,...,False,NaN,10.0,6.0,1.0,0.0,8,7,40,1
47,2004,2004,7,NaN,5.0,TX,False,NaN,7.374463,1.0,...,False,NaN,16.0,10.0,0.0,0.0,11,4,37,1
48,1983,1983,5,27.0,NaN,VA,True,7.0,8.313632,1.0,...,None,NaN,NaN,6.0,0.0,1.0,8,7,50,1
49,2003,2003,8,NaN,6.0,VA,True,NaN,6.752759,1.0,...,False,NaN,12.0,9.0,0.0,0.0,10,18,43,1

In [23]:
df.dtypes

source_year                 int64
year                        int64
month                       int64
day                       float64
wday                      float64
state                      object
is_male                      bool
child_race                float64
weight_pounds             float64
plurality                 float64
apgar_1min                float64
apgar_5min                float64
mother_residence_state     object
mother_race                 int64
mother_age                  int64
gestation_weeks           float64
lmp                        object
mother_married             object
mother_birth_state         object
cigarette_use              object
cigarettes_per_day        float64
alcohol_use                object
drinks_per_week           float64
weight_gain_pounds        float64
born_alive_alive          float64
born_alive_dead           float64
born_dead                 float64
ever_born                   int64
father_race                 int64
father_age                  int64
record_weight               int64
dtype: object

In [24]:
df.describe(include=[np.number])

,source_year,year,month,day,wday,child_race,weight_pounds,plurality,apgar_1min,apgar_5min,...,cigarettes_per_day,drinks_per_week,weight_gain_pounds,born_alive_alive,born_alive_dead,born_dead,ever_born,father_race,father_age,record_weight
count,50.000000,50.000000,50.000000,23.000000,27.000000,35.000000,50.000000,47.000000,27.000000,38.000000,...,1.0,1.0,26.000000,45.000000,45.000000,45.000000,50.000000,50.000000,50.00000,50.000000
mean,1991.280000,1991.280000,6.520000,19.565217,4.703704,6.857143,7.218287,1.106383,61.925926,37.210526,...,5.0,99.0,50.576923,7.088889,1.555556,2.044444,9.080000,26.540000,38.52000,1.240000
std,12.361956,12.361956,3.369975,8.156571,1.917828,1.647509,1.708543,0.311661,45.567301,42.544830,...,NaN,NaN,38.543662,2.466339,8.178563,8.218481,1.639313,30.331643,11.65182,0.431419
min,1969.000000,1969.000000,1.000000,4.000000,1.000000,4.000000,2.678616,1.000000,6.000000,6.000000,...,5.0,99.0,10.000000,1.000000,0.000000,0.000000,8.000000,4.000000,23.00000,1.000000
25%,1983.250000,1983.250000,4.000000,14.000000,4.000000,6.000000,6.413247,1.000000,8.000000,9.000000,...,5.0,99.0,16.250000,6.000000,0.000000,0.000000,8.000000,6.000000,31.00000,1.000000
50%,1994.000000,1994.000000,6.000000,22.000000,5.000000,7.000000,7.275255,1.000000,99.000000,9.000000,...,5.0,99.0,34.500000,7.000000,0.000000,0.000000,8.000000,7.000000,39.00000,1.000000
75%,2003.000000,2003.000000,9.000000,26.000000,6.000000,9.000000,8.359929,1.000000,99.000000,99.000000,...,5.0,99.0,99.000000,9.000000,0.000000,1.000000,10.000000,63.000000,41.75000,1.000000
max,2008.000000,2008.000000,12.000000,30.000000,7.000000,9.000000,11.062796,2.000000,99.000000,99.000000,...,5.0,99.0,99.000000,14.000000,55.000000,55.000000,15.000000,78.000000,99.00000,2.000000

In [25]:
df.columns

Index(['source_year', 'year', 'month', 'day', 'wday', 'state', 'is_male',
       'child_race', 'weight_pounds', 'plurality', 'apgar_1min', 'apgar_5min',
       'mother_residence_state', 'mother_race', 'mother_age',
       'gestation_weeks', 'lmp', 'mother_married', 'mother_birth_state',
       'cigarette_use', 'cigarettes_per_day', 'alcohol_use', 'drinks_per_week',
       'weight_gain_pounds', 'born_alive_alive', 'born_alive_dead',
       'born_dead', 'ever_born', 'father_race', 'father_age', 'record_weight'],
      dtype='object')

In [32]:
df.groupby(["year","born_alive_alive"])["year"].count()
#df[(df.year == 1970) & (df.born_alive_alive == '')]

print(df.source_year.unique())

[2005 2006 2007 2008 1998 2003 1969 1971 1974 1981 1984 1988 1989 1995
 2004 1993 1978 1983 1986 1987 2002 1999 2001]

In [53]:
query_2 = """

SELECT
    state AS  estado,
    COUNT(*) AS counter,
    (CASE
        WHEN child_race = 1 THEN "White"
        WHEN child_race = 2 THEN "Black"
        WHEN child_race = 3 THEN "American Indian"
        WHEN child_race = 4 THEN "Chinese"
        WHEN child_race = 5 THEN "Japanese"
        WHEN child_race = 6 THEN "Hawaiian"
        WHEN child_race = 7 THEN "Filipino"
        WHEN child_race = 18 THEN "Asian Indian"
        WHEN child_race = 28 THEN "Korean"
        WHEN child_race = 39 THEN "Samoan"
        WHEN child_race = 48 THEN "Vietnamese"
        ELSE "Italiano/other..."
        END) as raza
FROM `bigquery-public-data.samples.natality`
WHERE
    state IS NOT NULL AND
    child_race IS NOT NULL AND
    year >= 1970 AND year < 1980
GROUP BY
    estado, raza
ORDER BY
    estado



"""

In [54]:
query_job_2 = client.query(query_2)

In [55]:
df2 = query_job_2.to_dataframe()
df2

    estado  counter             raza
0       AK       69         Hawaiian
1       AK    11614  American Indian
2       AK       70          Chinese
3       AK    36396            White
4       AK      384         Filipino
..     ...      ...              ...
403     WY       11         Hawaiian
404     WY    36996            White
405     WY      463            Black
406     WY     1247  American Indian
407     WY       62         Japanese

[408 rows x 3 columns]

In [56]:
query_3 = """
WITH Race70 AS (
SELECT 
    state AS  estado,
    COUNT(*) AS counter,
    (CASE
        WHEN child_race = 1 THEN "White"
        WHEN child_race = 2 THEN "Black"
        WHEN child_race = 3 THEN "American Indian"
        WHEN child_race = 4 THEN "Chinese"
        WHEN child_race = 5 THEN "Japanese"
        WHEN child_race = 6 THEN "Hawaiian"
        WHEN child_race = 7 THEN "Filipino"
        WHEN child_race = 18 THEN "Asian Indian"
        WHEN child_race = 28 THEN "Korean"
        WHEN child_race = 39 THEN "Samoan"
        WHEN child_race = 48 THEN "Vietnamese"
        ELSE "Italiano/other..."
        END) as raza
FROM (
    SELECT year, state, child_race
    FROM `bigquery-public-data.samples.natality`
    )
WHERE 
    state IS NOT NULL AND 
    child_race IS NOT NULL AND 
    year >= 1970 AND year < 1980
GROUP BY 
    estado, raza
)
SELECT 
    r70.estado, 
    r70.raza
FROM (
    SELECT 
    ARRAY_AGG(Race70 ORDER BY Race70.counter DESC LIMIT 1)[OFFSET(0)] AS r70
    FROM Race70
    GROUP BY Race70.estado 
    ORDER BY Race70.estado
)
"""

In [57]:
query_job_3 = client.query(query_3)

In [58]:
df2 = query_job_3.to_dataframe()
df2

   estado      raza
0      AK     White
1      AL     White
2      AR     White
3      AZ     White
4      CA     White
5      CO     White
6      CT     White
7      DC     Black
8      DE     White
9      FL     White
10     GA     White
11     HI  Hawaiian
12     IA     White
13     ID     White
14     IL     White
15     IN     White
16     KS     White
17     KY     White
18     LA     White
19     MA     White
20     MD     White
21     ME     White
22     MI     White
23     MN     White
24     MO     White
25     MS     White
26     MT     White
27     NC     White
28     ND     White
29     NE     White
30     NH     White
31     NJ     White
32     NM     White
33     NV     White
34     NY     White
35     OH     White
36     OK     White
37     OR     White
38     PA     White
39     RI     White
40     SC     White
41     SD     White
42     TN     White
43     TX     White
44     UT     White
45     VA     White
46     VT     White
47     WA     White
48     WI     White
49     WV     White
50     WY     White

In [59]:
query_u = """
WITH Race70 AS (
SELECT 
    state AS  estado,
    COUNT(*) AS counter,
    (CASE
        WHEN child_race = 1 THEN "White"
        WHEN child_race = 2 THEN "Black"
        WHEN child_race = 3 THEN "American Indian"
        WHEN child_race = 4 THEN "Chinese"
        WHEN child_race = 5 THEN "Japanese"
        WHEN child_race = 6 THEN "Hawaiian"
        WHEN child_race = 7 THEN "Filipino"
        WHEN child_race = 18 THEN "Asian Indian"
        WHEN child_race = 28 THEN "Korean"
        WHEN child_race = 39 THEN "Samoan"
        WHEN child_race = 48 THEN "Vietnamese"
        ELSE "Italiano/other..."
        END) as raza
FROM (
    SELECT year, state, child_race
    FROM `bigquery-public-data.samples.natality`
    )
WHERE 
    state IS NOT NULL AND 
    child_race IS NOT NULL AND 
    year >= 1970 AND year < 1980
GROUP BY 
    estado, raza
),
Race80 AS (
SELECT 
    state AS  estado,
    COUNT(*) AS counter,
    (CASE
        WHEN child_race = 1 THEN "White"
        WHEN child_race = 2 THEN "Black"
        WHEN child_race = 3 THEN "American Indian"
        WHEN child_race = 4 THEN "Chinese"
        WHEN child_race = 5 THEN "Japanese"
        WHEN child_race = 6 THEN "Hawaiian"
        WHEN child_race = 7 THEN "Filipino"
        WHEN child_race = 18 THEN "Asian Indian"
        WHEN child_race = 28 THEN "Korean"
        WHEN child_race = 39 THEN "Samoan"
        WHEN child_race = 48 THEN "Vietnamese"
        ELSE "Italiano/other..."
        END) as raza
FROM (
    SELECT year, state, child_race
    FROM `bigquery-public-data.samples.natality`
    )
WHERE 
    state IS NOT NULL AND 
    child_race IS NOT NULL AND 
    year >= 1980 AND year < 1990
GROUP BY 
    estado, raza
),
Race90 AS (
SELECT 
    state AS  estado,
    COUNT(*) AS counter,
    (CASE
        WHEN child_race = 1 THEN "White"
        WHEN child_race = 2 THEN "Black"
        WHEN child_race = 3 THEN "American Indian"
        WHEN child_race = 4 THEN "Chinese"
        WHEN child_race = 5 THEN "Japanese"
        WHEN child_race = 6 THEN "Hawaiian"
        WHEN child_race = 7 THEN "Filipino"
        WHEN child_race = 18 THEN "Asian Indian"
        WHEN child_race = 28 THEN "Korean"
        WHEN child_race = 39 THEN "Samoan"
        WHEN child_race = 48 THEN "Vietnamese"
        ELSE "Italiano/other..."
        END) as raza
FROM (
    SELECT year, state, child_race
    FROM `bigquery-public-data.samples.natality`
    )
WHERE 
    state IS NOT NULL AND 
    child_race IS NOT NULL AND 
    year >= 1990 AND year < 2000
GROUP BY 
    estado, raza
),
Race00 AS (
SELECT 
    state AS  estado,
    COUNT(*) AS counter,
    (CASE
        WHEN child_race = 1 THEN "White"
        WHEN child_race = 2 THEN "Black"
        WHEN child_race = 3 THEN "American Indian"
        WHEN child_race = 4 THEN "Chinese"
        WHEN child_race = 5 THEN "Japanese"
        WHEN child_race = 6 THEN "Hawaiian"
        WHEN child_race = 7 THEN "Filipino"
        WHEN child_race = 18 THEN "Asian Indian"
        WHEN child_race = 28 THEN "Korean"
        WHEN child_race = 39 THEN "Samoan"
        WHEN child_race = 48 THEN "Vietnamese"
        ELSE "Italiano/other..."
        END) as raza
FROM (
    SELECT year, state, child_race
    FROM `bigquery-public-data.samples.natality`
    )
WHERE 
    state IS NOT NULL AND 
    child_race IS NOT NULL AND 
    year >= 2000 AND year < 2010
GROUP BY 
    estado, raza
)
SELECT 
    r70.estado, 
    r70.raza,
    r80.raza,
    r90.raza,
    r00.raza
FROM (
    SELECT 
    ARRAY_AGG(Race70 ORDER BY Race70.counter DESC LIMIT 1)[OFFSET(0)] AS r70,
    ARRAY_AGG(Race80 ORDER BY Race80.counter DESC LIMIT 1)[OFFSET(0)] AS r80,
    ARRAY_AGG(Race90 ORDER BY Race90.counter DESC LIMIT 1)[OFFSET(0)] AS r90,
    ARRAY_AGG(Race00 ORDER BY Race00.counter DESC LIMIT 1)[OFFSET(0)] AS r00
    FROM Race70,Race80,Race90,Race00
    WHERE Race70.estado = Race80.estado
    GROUP BY Race70.estado 
    ORDER BY Race70.estado)

"""

In [60]:
query_job_u = client.query(query_u)

In [61]:
dfu = query_job_u.to_dataframe()
dfu

   estado      raza    raza_1             raza_2             raza_3
0      AK     White     White  Italiano/other...  Italiano/other...
1      AL     White     White  Italiano/other...  Italiano/other...
2      AR     White     White  Italiano/other...  Italiano/other...
3      AZ     White     White  Italiano/other...  Italiano/other...
4      CA     White     White  Italiano/other...  Italiano/other...
5      CO     White     White  Italiano/other...  Italiano/other...
6      CT     White     White  Italiano/other...  Italiano/other...
7      DC     Black     Black  Italiano/other...  Italiano/other...
8      DE     White     White  Italiano/other...  Italiano/other...
9      FL     White     White  Italiano/other...  Italiano/other...
10     GA     White     White  Italiano/other...  Italiano/other...
11     HI  Hawaiian  Hawaiian  Italiano/other...  Italiano/other...
12     IA     White     White  Italiano/other...  Italiano/other...
13     ID     White     White  Italiano/other...  Italiano/other...
14     IL     White     White  Italiano/other...  Italiano/other...
15     IN     White     White  Italiano/other...  Italiano/other...
16     KS     White     White  Italiano/other...  Italiano/other...
17     KY     White     White  Italiano/other...  Italiano/other...
18     LA     White     White  Italiano/other...  Italiano/other...
19     MA     White     White  Italiano/other...  Italiano/other...
20     MD     White     White  Italiano/other...  Italiano/other...
21     ME     White     White  Italiano/other...  Italiano/other...
22     MI     White     White  Italiano/other...  Italiano/other...
23     MN     White     White  Italiano/other...  Italiano/other...
24     MO     White     White  Italiano/other...  Italiano/other...
25     MS     White     White  Italiano/other...  Italiano/other...
26     MT     White     White  Italiano/other...  Italiano/other...
27     NC     White     White  Italiano/other...  Italiano/other...
28     ND     White     White  Italiano/other...  Italiano/other...
29     NE     White     White  Italiano/other...  Italiano/other...
30     NH     White     White  Italiano/other...  Italiano/other...
31     NJ     White     White  Italiano/other...  Italiano/other...
32     NM     White     White  Italiano/other...  Italiano/other...
33     NV     White     White  Italiano/other...  Italiano/other...
34     NY     White     White  Italiano/other...  Italiano/other...
35     OH     White     White  Italiano/other...  Italiano/other...
36     OK     White     White  Italiano/other...  Italiano/other...
37     OR     White     White  Italiano/other...  Italiano/other...
38     PA     White     White  Italiano/other...  Italiano/other...
39     RI     White     White  Italiano/other...  Italiano/other...
40     SC     White     White  Italiano/other...  Italiano/other...
41     SD     White     White  Italiano/other...  Italiano/other...
42     TN     White     White  Italiano/other...  Italiano/other...
43     TX     White     White  Italiano/other...  Italiano/other...
44     UT     White     White  Italiano/other...  Italiano/other...
45     VA     White     White  Italiano/other...  Italiano/other...
46     VT     White     White  Italiano/other...  Italiano/other...
47     WA     White     White  Italiano/other...  Italiano/other...
48     WI     White     White  Italiano/other...  Italiano/other...
49     WV     White     White  Italiano/other...  Italiano/other...
50     WY     White     White  Italiano/other...  Italiano/other...

In [62]:
query_razas2 = """
    WITH Race70 AS (
SELECT 
    state AS  estado,
    COUNT(*) AS counter,
    (CASE
        WHEN child_race = 1 THEN "White"
        WHEN child_race = 2 THEN "Black"
        WHEN child_race = 3 THEN "American Indian"
        WHEN child_race = 4 THEN "Chinese"
        WHEN child_race = 5 THEN "Japanese"
        WHEN child_race = 6 THEN "Hawaiian"
        WHEN child_race = 7 THEN "Filipino"
        WHEN child_race = 18 THEN "Asian Indian"
        WHEN child_race = 28 THEN "Korean"
        WHEN child_race = 39 THEN "Samoan"
        WHEN child_race = 48 THEN "Vietnamese"
        ELSE "Italiano/other..."
        END) as raza
FROM (
    SELECT year, state, child_race
    FROM `bigquery-public-data.samples.natality`
    )
WHERE 
    state IS NOT NULL AND 
    child_race IS NOT NULL AND 
    year >= 1970 AND year < 1980
GROUP BY 
    estado, raza
),
Race80 AS (
SELECT 
    state AS  estado,
    COUNT(*) AS counter,
    (CASE
        WHEN child_race = 1 THEN "White"
        WHEN child_race = 2 THEN "Black"
        WHEN child_race = 3 THEN "American Indian"
        WHEN child_race = 4 THEN "Chinese"
        WHEN child_race = 5 THEN "Japanese"
        WHEN child_race = 6 THEN "Hawaiian"
        WHEN child_race = 7 THEN "Filipino"
        WHEN child_race = 18 THEN "Asian Indian"
        WHEN child_race = 28 THEN "Korean"
        WHEN child_race = 39 THEN "Samoan"
        WHEN child_race = 48 THEN "Vietnamese"
        ELSE "Italiano/other..."
        END) as raza
FROM (
    SELECT year, state, child_race
    FROM `bigquery-public-data.samples.natality`
    )
WHERE 
    state IS NOT NULL AND 
    child_race IS NOT NULL AND 
    year >= 1980 AND year < 1990
GROUP BY 
    estado, raza
),
Race90 AS (
SELECT 
    state AS  estado,
    COUNT(*) AS counter,
    (CASE
        WHEN child_race = 1 THEN "White"
        WHEN child_race = 2 THEN "Black"
        WHEN child_race = 3 THEN "American Indian"
        WHEN child_race = 4 THEN "Chinese"
        WHEN child_race = 5 THEN "Japanese"
        WHEN child_race = 6 THEN "Hawaiian"
        WHEN child_race = 7 THEN "Filipino"
        WHEN child_race = 18 THEN "Asian Indian"
        WHEN child_race = 28 THEN "Korean"
        WHEN child_race = 39 THEN "Samoan"
        WHEN child_race = 48 THEN "Vietnamese"
        ELSE "Italiano/other..."
        END) as raza
FROM (
    SELECT year, state, child_race
    FROM `bigquery-public-data.samples.natality`
    )
WHERE 
    state IS NOT NULL AND 
    child_race IS NOT NULL AND 
    year >= 1990 AND year < 2000
GROUP BY 
    estado, raza
),
Race00 AS (
SELECT 
    state AS  estado,
    COUNT(*) AS counter,
    (CASE
        WHEN child_race = 1 THEN "White"
        WHEN child_race = 2 THEN "Black"
        WHEN child_race = 3 THEN "American Indian"
        WHEN child_race = 4 THEN "Chinese"
        WHEN child_race = 5 THEN "Japanese"
        WHEN child_race = 6 THEN "Hawaiian"
        WHEN child_race = 7 THEN "Filipino"
        WHEN child_race = 18 THEN "Asian Indian"
        WHEN child_race = 28 THEN "Korean"
        WHEN child_race = 39 THEN "Samoan"
        WHEN child_race = 48 THEN "Vietnamese"
        ELSE "Italiano/other..."
        END) as raza
FROM (
    SELECT year, state, child_race
    FROM `bigquery-public-data.samples.natality`
    )
WHERE 
    state IS NOT NULL AND 
    child_race IS NOT NULL AND 
    year >= 2000
GROUP BY 
    estado, raza
)
SELECT 
    r70.estado, 
    r70.raza,
    r80.raza,
    r90.raza,
    r00.raza
FROM (
    SELECT 
    ARRAY_AGG(Race70 ORDER BY Race70.counter DESC LIMIT 1)[OFFSET(0)] AS r70,
    ARRAY_AGG(Race80 ORDER BY Race80.counter DESC LIMIT 1)[OFFSET(0)] AS r80,
    ARRAY_AGG(Race90 ORDER BY Race90.counter DESC LIMIT 1)[OFFSET(0)] AS r90,
    ARRAY_AGG(Race00 ORDER BY Race00.counter DESC LIMIT 1)[OFFSET(0)] AS r00
    FROM Race70,Race80,Race90,Race00
    WHERE Race70.estado = Race80.estado
    GROUP BY Race70.estado 
    ORDER BY Race70.estado
)
"""

In [78]:
query_act = """
WITH Race70 AS (
SELECT
    state AS  estado70,
    COUNT(*) AS counter70,
    (CASE
        WHEN child_race = 1 THEN "White"
        WHEN child_race = 2 THEN "Black"
        WHEN child_race = 3 THEN "American Indian"
        WHEN child_race = 4 THEN "Chinese"
        WHEN child_race = 5 THEN "Japanese"
        WHEN child_race = 6 THEN "Hawaiian"
        WHEN child_race = 7 THEN "Filipino"
        WHEN child_race = 18 THEN "Asian Indian"
        WHEN child_race = 28 THEN "Korean"
        WHEN child_race = 39 THEN "Samoan"
        WHEN child_race = 48 THEN "Vietnamese"
        ELSE "Italiano/other..."
        END) as raza70
FROM (
    SELECT year, state, child_race
    FROM `bigquery-public-data.samples.natality`
    )
WHERE
    state IS NOT NULL AND
    child_race IS NOT NULL AND
    year >= 1970 AND year < 1980
GROUP BY
    estado70, raza70
),
Race80 AS(
SELECT
    state AS  estado80,
    COUNT(*) AS counter80,
    (CASE
        WHEN child_race = 1 THEN "White"
        WHEN child_race = 2 THEN "Black"
        WHEN child_race = 3 THEN "American Indian"
        WHEN child_race = 4 THEN "Chinese"
        WHEN child_race = 5 THEN "Japanese"
        WHEN child_race = 6 THEN "Hawaiian"
        WHEN child_race = 7 THEN "Filipino"
        WHEN child_race = 18 THEN "Asian Indian"
        WHEN child_race = 28 THEN "Korean"
        WHEN child_race = 39 THEN "Samoan"
        WHEN child_race = 48 THEN "Vietnamese"
        ELSE "Italiano/other..."
        END) as raza80
FROM (
    SELECT year, state, child_race
    FROM `bigquery-public-data.samples.natality`
    )
WHERE
    state IS NOT NULL AND
    child_race IS NOT NULL AND
    year >= 1980 AND year < 1990
GROUP BY
    estado80, raza80
),
Race90 AS (
SELECT
    state AS  estado90,
    COUNT(*) AS counter90,
    (CASE
        WHEN child_race = 1 THEN "White"
        WHEN child_race = 2 THEN "Black"
        WHEN child_race = 3 THEN "American Indian"
        WHEN child_race = 4 THEN "Chinese"
        WHEN child_race = 5 THEN "Japanese"
        WHEN child_race = 6 THEN "Hawaiian"
        WHEN child_race = 7 THEN "Filipino"
        WHEN child_race = 18 THEN "Asian Indian"
        WHEN child_race = 28 THEN "Korean"
        WHEN child_race = 39 THEN "Samoan"
        WHEN child_race = 48 THEN "Vietnamese"
        ELSE "Italiano/other..."
        END) as raza90
FROM (
    SELECT year, state, child_race
    FROM `bigquery-public-data.samples.natality`
    )
WHERE
    state IS NOT NULL AND
    child_race IS NOT NULL AND
    year >= 1990 AND year < 2000
GROUP BY
    estado90, raza90
),
Race00 AS (
SELECT
    state AS  estado00,
    COUNT(*) AS counter00,
    (CASE
        WHEN child_race = 1 THEN "White"
        WHEN child_race = 2 THEN "Black"
        WHEN child_race = 3 THEN "American Indian"
        WHEN child_race = 4 THEN "Chinese"
        WHEN child_race = 5 THEN "Japanese"
        WHEN child_race = 6 THEN "Hawaiian"
        WHEN child_race = 7 THEN "Filipino"
        WHEN child_race = 18 THEN "Asian Indian"
        WHEN child_race = 28 THEN "Korean"
        WHEN child_race = 39 THEN "Samoan"
        WHEN child_race = 48 THEN "Vietnamese"
        ELSE "Italiano/other..."
        END) as raza00
FROM (
    SELECT year, state, child_race
    FROM `bigquery-public-data.samples.natality`
    )
WHERE
    state IS NOT NULL AND
    child_race IS NOT NULL AND
    year >= 2000 AND year < 2010
GROUP BY
    estado00, raza00
)
SELECT
    r70.estado70,
    r70.raza70,
    r80.raza80,
    r90.raza90,
    r00.raza00
FROM (
    SELECT
    ARRAY_AGG(Race70 ORDER BY Race70.counter70 DESC LIMIT 1)[OFFSET(0)] AS r70,
    ARRAY_AGG(Race80 ORDER BY Race80.counter80 DESC LIMIT 1)[OFFSET(0)] AS r80,
    ARRAY_AGG(Race90 ORDER BY Race90.counter90 DESC LIMIT 1)[OFFSET(0)] AS r90,
    ARRAY_AGG(Race00 ORDER BY Race00.counter00 DESC LIMIT 1)[OFFSET(0)] AS r00
    FROM Race70, Race80, Race90, Race00
    WHERE Race70.estado70 = Race80.estado80
    GROUP BY Race70.estado70
    ORDER BY Race70.estado70
)
"""

In [63]:
query_job_razas = client.query(query_razas2)

In [64]:
dfrazas = query_job_razas.to_dataframe()
dfrazas

   estado      raza    raza_1             raza_2             raza_3
0      AK     White     White  Italiano/other...  Italiano/other...
1      AL     White     White  Italiano/other...  Italiano/other...
2      AR     White     White  Italiano/other...  Italiano/other...
3      AZ     White     White  Italiano/other...  Italiano/other...
4      CA     White     White  Italiano/other...  Italiano/other...
5      CO     White     White  Italiano/other...  Italiano/other...
6      CT     White     White  Italiano/other...  Italiano/other...
7      DC     Black     Black  Italiano/other...  Italiano/other...
8      DE     White     White  Italiano/other...  Italiano/other...
9      FL     White     White  Italiano/other...  Italiano/other...
10     GA     White     White  Italiano/other...  Italiano/other...
11     HI  Hawaiian  Hawaiian  Italiano/other...  Italiano/other...
12     IA     White     White  Italiano/other...  Italiano/other...
13     ID     White     White  Italiano/other...  Italiano/other...
14     IL     White     White  Italiano/other...  Italiano/other...
15     IN     White     White  Italiano/other...  Italiano/other...
16     KS     White     White  Italiano/other...  Italiano/other...
17     KY     White     White  Italiano/other...  Italiano/other...
18     LA     White     White  Italiano/other...  Italiano/other...
19     MA     White     White  Italiano/other...  Italiano/other...
20     MD     White     White  Italiano/other...  Italiano/other...
21     ME     White     White  Italiano/other...  Italiano/other...
22     MI     White     White  Italiano/other...  Italiano/other...
23     MN     White     White  Italiano/other...  Italiano/other...
24     MO     White     White  Italiano/other...  Italiano/other...
25     MS     White     White  Italiano/other...  Italiano/other...
26     MT     White     White  Italiano/other...  Italiano/other...
27     NC     White     White  Italiano/other...  Italiano/other...
28     ND     White     White  Italiano/other...  Italiano/other...
29     NE     White     White  Italiano/other...  Italiano/other...
30     NH     White     White  Italiano/other...  Italiano/other...
31     NJ     White     White  Italiano/other...  Italiano/other...
32     NM     White     White  Italiano/other...  Italiano/other...
33     NV     White     White  Italiano/other...  Italiano/other...
34     NY     White     White  Italiano/other...  Italiano/other...
35     OH     White     White  Italiano/other...  Italiano/other...
36     OK     White     White  Italiano/other...  Italiano/other...
37     OR     White     White  Italiano/other...  Italiano/other...
38     PA     White     White  Italiano/other...  Italiano/other...
39     RI     White     White  Italiano/other...  Italiano/other...
40     SC     White     White  Italiano/other...  Italiano/other...
41     SD     White     White  Italiano/other...  Italiano/other...
42     TN     White     White  Italiano/other...  Italiano/other...
43     TX     White     White  Italiano/other...  Italiano/other...
44     UT     White     White  Italiano/other...  Italiano/other...
45     VA     White     White  Italiano/other...  Italiano/other...
46     VT     White     White  Italiano/other...  Italiano/other...
47     WA     White     White  Italiano/other...  Italiano/other...
48     WI     White     White  Italiano/other...  Italiano/other...
49     WV     White     White  Italiano/other...  Italiano/other...
50     WY     White     White  Italiano/other...  Italiano/other...

In [68]:
df3 = pd.merge(left=df_nacimientos, right=dfu, left_on='estado', right_on='estado')
df3

,estado,B70,B80,B90,B00,Male,Female,Weight,raza,raza_1,raza_2,raza_3
0,AK,1529,4529,4971,2714,3391,3396,2.464,White,White,Italiano/other...,Italiano/other...
1,AL,14866,26254,33540,21033,23479,23407,2.277,White,White,Italiano/other...,Italiano/other...
2,AR,5703,14453,16504,10678,11598,11751,2.318,White,White,Italiano/other...,Italiano/other...
3,AZ,6523,17201,36109,25765,20775,20761,2.346,White,White,Italiano/other...,Italiano/other...
4,CA,56624,147762,274371,159740,156282,157163,2.405,White,White,Italiano/other...,Italiano/other...
5,CO,12704,23079,32601,22479,22324,22024,2.292,White,White,Italiano/other...,Italiano/other...
6,CT,6887,19684,30100,18537,18463,18173,2.384,White,White,Italiano/other...,Italiano/other...
7,DC,4105,7863,12071,6088,7373,7232,2.258,Black,Black,Italiano/other...,Italiano/other...
8,DE,1517,3398,7047,4769,4082,4052,2.302,White,White,Italiano/other...,Italiano/other...
9,FL,35721,67570,101555,65804,66529,66131,2.324,White,White,Italiano/other...,Italiano/other...
10,GA,14105,31195,62185,44634,37509,37113,2.298,White,White,Italiano/other...,Italiano/other...
11,HI,2728,6861,8141,5025,5438,5708,2.357,Hawaiian,Hawaiian,Italiano/other...,Italiano/other...
12,IA,12318,16850,20552,12578,15456,15080,2.432,White,White,Italiano/other...,Italiano/other...
13,ID,3353,6754,7617,6116,5871,5893,2.439,White,White,Italiano/other...,Italiano/other...
14,IL,54274,82399,109431,67318,76938,75949,2.350,White,White,Italiano/other...,Italiano/other...
15,IN,17700,35039,45554,29408,31038,31229,2.363,White,White,Italiano/other...,Italiano/other...
16,KS,9439,15872,18728,12359,13966,13746,2.366,White,White,Italiano/other...,Italiano/other...
17,KY,14359,21149,25976,17372,19535,19192,2.344,White,White,Italiano/other...,Italiano/other...
18,LA,21035,35766,37086,21762,28713,28151,2.265,White,White,Italiano/other...,Italiano/other...
19,MA,16547,36487,58530,39061,36887,36410,2.408,White,White,Italiano/other...,Italiano/other...
20,MD,12803,26584,40107,27492,26122,26119,2.339,White,White,Italiano/other...,Italiano/other...
21,ME,4506,6193,8076,4632,5784,5740,2.435,White,White,Italiano/other...,Italiano/other...
22,MI,44665,62224,81500,47664,58288,57173,2.346,White,White,Italiano/other...,Italiano/other...
23,MN,14967,28263,37706,25120,25919,25775,2.424,White,White,Italiano/other...,Italiano/other...
24,MO,25039,34825,45850,28357,32753,32995,2.322,White,White,Italiano/other...,Italiano/other...
25,MS,9387,19577,21223,13200,15730,15554,2.281,White,White,Italiano/other...,Italiano/other...
26,MT,3678,5196,5052,3493,4328,4267,2.428,White,White,Italiano/other...,Italiano/other...
27,NC,22560,39162,58243,40127,39352,39175,2.284,White,White,Italiano/other...,Italiano/other...
28,ND,1821,4373,5784,3242,3776,3625,2.397,White,White,Italiano/other...,Italiano/other...
29,NE,7277,12034,15101,9573,10710,10614,2.361,White,White,Italiano/other...,Italiano/other...
30,NH,3699,6174,7534,4925,5614,5366,2.487,White,White,Italiano/other...,Italiano/other...
31,NJ,18583,43139,73119,48455,44384,44599,2.365,White,White,Italiano/other...,Italiano/other...
32,NM,2880,7833,11259,6312,6972,6992,2.357,White,White,Italiano/other...,Italiano/other...
33,NV,2598,6386,12585,9980,7707,7748,2.306,White,White,Italiano/other...,Italiano/other...
34,NY,69364,117076,167542,99497,111583,109968,2.371,White,White,Italiano/other...,Italiano/other...
35,OH,38654,71705,92355,55657,63514,62471,2.358,White,White,Italiano/other...,Italiano/other...
36,OK,11305,21504,22225,13831,17085,16823,2.356,White,White,Italiano/other...,Italiano/other...
37,OR,10466,18117,23200,14763,16373,16312,2.441,White,White,Italiano/other...,Italiano/other...
38,PA,28736,71515,90686,51544,59655,58848,2.355,White,White,Italiano/other...,Italiano/other...
39,RI,4148,5959,9093,6028,6181,6120,2.356,White,White,Italiano/other...,Italiano/other...
40,SC,14136,21814,27763,17073,20091,19669,2.292,White,White,Italiano/other...,Italiano/other...
41,SD,1897,5042,6175,3930,4181,4185,2.396,White,White,Italiano/other...,Italiano/other...
42,TN,18556,31035,43236,28085,29623,29762,2.260,White,White,Italiano/other...,Italiano/other...
43,TX,58549,124826,160076,109302,111357,110908,2.334,White,White,Italiano/other...,Italiano/other...
44,UT,7307,16772,20597,14146,14676,14126,2.371,White,White,Italiano/other...,Italiano/other...
45,VA,18236,35158,49755,33618,33623,33630,2.341,White,White,Italiano/other...,Italiano/other...
46,VT,2081,3163,3612,1958,2729,2612,2.381,White,White,Italiano/other...,Italiano/other...
47,WA,11431,29364,37868,23735,25193,25165,2.455,White,White,Italiano/other...,Italiano/other...
48,WI,18640,31430,36660,21630,26705,26456,2.425,White,White,Italiano/other...,Italiano/other...
49,WV,6873,10023,10711,6245,8479,8203,2.323,White,White,Italiano/other...,Italiano/other...
50,WY,1306,3064,2412,1296,1979,2040,2.465,White,White,Italiano/other...,Italiano/other...

In [76]:
%%time
pruebamerge = pd.merge(df_nacimientos, dfu)
pruebamerge

CPU times: user 6.25 ms, sys: 1.09 ms, total: 7.34 ms
Wall time: 6.63 ms

,estado,B70,B80,B90,B00,Male,Female,Weight,raza,raza_1,raza_2,raza_3
0,AK,1529,4529,4971,2714,3391,3396,2.464,White,White,Italiano/other...,Italiano/other...
1,AL,14866,26254,33540,21033,23479,23407,2.277,White,White,Italiano/other...,Italiano/other...
2,AR,5703,14453,16504,10678,11598,11751,2.318,White,White,Italiano/other...,Italiano/other...
3,AZ,6523,17201,36109,25765,20775,20761,2.346,White,White,Italiano/other...,Italiano/other...
4,CA,56624,147762,274371,159740,156282,157163,2.405,White,White,Italiano/other...,Italiano/other...
5,CO,12704,23079,32601,22479,22324,22024,2.292,White,White,Italiano/other...,Italiano/other...
6,CT,6887,19684,30100,18537,18463,18173,2.384,White,White,Italiano/other...,Italiano/other...
7,DC,4105,7863,12071,6088,7373,7232,2.258,Black,Black,Italiano/other...,Italiano/other...
8,DE,1517,3398,7047,4769,4082,4052,2.302,White,White,Italiano/other...,Italiano/other...
9,FL,35721,67570,101555,65804,66529,66131,2.324,White,White,Italiano/other...,Italiano/other...
10,GA,14105,31195,62185,44634,37509,37113,2.298,White,White,Italiano/other...,Italiano/other...
11,HI,2728,6861,8141,5025,5438,5708,2.357,Hawaiian,Hawaiian,Italiano/other...,Italiano/other...
12,IA,12318,16850,20552,12578,15456,15080,2.432,White,White,Italiano/other...,Italiano/other...
13,ID,3353,6754,7617,6116,5871,5893,2.439,White,White,Italiano/other...,Italiano/other...
14,IL,54274,82399,109431,67318,76938,75949,2.350,White,White,Italiano/other...,Italiano/other...
15,IN,17700,35039,45554,29408,31038,31229,2.363,White,White,Italiano/other...,Italiano/other...
16,KS,9439,15872,18728,12359,13966,13746,2.366,White,White,Italiano/other...,Italiano/other...
17,KY,14359,21149,25976,17372,19535,19192,2.344,White,White,Italiano/other...,Italiano/other...
18,LA,21035,35766,37086,21762,28713,28151,2.265,White,White,Italiano/other...,Italiano/other...
19,MA,16547,36487,58530,39061,36887,36410,2.408,White,White,Italiano/other...,Italiano/other...
20,MD,12803,26584,40107,27492,26122,26119,2.339,White,White,Italiano/other...,Italiano/other...
21,ME,4506,6193,8076,4632,5784,5740,2.435,White,White,Italiano/other...,Italiano/other...
22,MI,44665,62224,81500,47664,58288,57173,2.346,White,White,Italiano/other...,Italiano/other...
23,MN,14967,28263,37706,25120,25919,25775,2.424,White,White,Italiano/other...,Italiano/other...
24,MO,25039,34825,45850,28357,32753,32995,2.322,White,White,Italiano/other...,Italiano/other...
25,MS,9387,19577,21223,13200,15730,15554,2.281,White,White,Italiano/other...,Italiano/other...
26,MT,3678,5196,5052,3493,4328,4267,2.428,White,White,Italiano/other...,Italiano/other...
27,NC,22560,39162,58243,40127,39352,39175,2.284,White,White,Italiano/other...,Italiano/other...
28,ND,1821,4373,5784,3242,3776,3625,2.397,White,White,Italiano/other...,Italiano/other...
29,NE,7277,12034,15101,9573,10710,10614,2.361,White,White,Italiano/other...,Italiano/other...
30,NH,3699,6174,7534,4925,5614,5366,2.487,White,White,Italiano/other...,Italiano/other...
31,NJ,18583,43139,73119,48455,44384,44599,2.365,White,White,Italiano/other...,Italiano/other...
32,NM,2880,7833,11259,6312,6972,6992,2.357,White,White,Italiano/other...,Italiano/other...
33,NV,2598,6386,12585,9980,7707,7748,2.306,White,White,Italiano/other...,Italiano/other...
34,NY,69364,117076,167542,99497,111583,109968,2.371,White,White,Italiano/other...,Italiano/other...
35,OH,38654,71705,92355,55657,63514,62471,2.358,White,White,Italiano/other...,Italiano/other...
36,OK,11305,21504,22225,13831,17085,16823,2.356,White,White,Italiano/other...,Italiano/other...
37,OR,10466,18117,23200,14763,16373,16312,2.441,White,White,Italiano/other...,Italiano/other...
38,PA,28736,71515,90686,51544,59655,58848,2.355,White,White,Italiano/other...,Italiano/other...
39,RI,4148,5959,9093,6028,6181,6120,2.356,White,White,Italiano/other...,Italiano/other...
40,SC,14136,21814,27763,17073,20091,19669,2.292,White,White,Italiano/other...,Italiano/other...
41,SD,1897,5042,6175,3930,4181,4185,2.396,White,White,Italiano/other...,Italiano/other...
42,TN,18556,31035,43236,28085,29623,29762,2.260,White,White,Italiano/other...,Italiano/other...
43,TX,58549,124826,160076,109302,111357,110908,2.334,White,White,Italiano/other...,Italiano/other...
44,UT,7307,16772,20597,14146,14676,14126,2.371,White,White,Italiano/other...,Italiano/other...
45,VA,18236,35158,49755,33618,33623,33630,2.341,White,White,Italiano/other...,Italiano/other...
46,VT,2081,3163,3612,1958,2729,2612,2.381,White,White,Italiano/other...,Italiano/other...
47,WA,11431,29364,37868,23735,25193,25165,2.455,White,White,Italiano/other...,Italiano/other...
48,WI,18640,31430,36660,21630,26705,26456,2.425,White,White,Italiano/other...,Italiano/other...
49,WV,6873,10023,10711,6245,8479,8203,2.323,White,White,Italiano/other...,Italiano/other...
50,WY,1306,3064,2412,1296,1979,2040,2.465,White,White,Italiano/other...,Italiano/other...

In [77]:
%%time
pruebajoin = df_nacimientos.join(dfu.set_index('estado'), on='estado')
pruebajoin

CPU times: user 3.87 ms, sys: 401 Âµs, total: 4.27 ms
Wall time: 4.14 ms

,estado,B70,B80,B90,B00,Male,Female,Weight,raza,raza_1,raza_2,raza_3
0,AK,1529,4529,4971,2714,3391,3396,2.464,White,White,Italiano/other...,Italiano/other...
1,AL,14866,26254,33540,21033,23479,23407,2.277,White,White,Italiano/other...,Italiano/other...
2,AR,5703,14453,16504,10678,11598,11751,2.318,White,White,Italiano/other...,Italiano/other...
3,AZ,6523,17201,36109,25765,20775,20761,2.346,White,White,Italiano/other...,Italiano/other...
4,CA,56624,147762,274371,159740,156282,157163,2.405,White,White,Italiano/other...,Italiano/other...
5,CO,12704,23079,32601,22479,22324,22024,2.292,White,White,Italiano/other...,Italiano/other...
6,CT,6887,19684,30100,18537,18463,18173,2.384,White,White,Italiano/other...,Italiano/other...
7,DC,4105,7863,12071,6088,7373,7232,2.258,Black,Black,Italiano/other...,Italiano/other...
8,DE,1517,3398,7047,4769,4082,4052,2.302,White,White,Italiano/other...,Italiano/other...
9,FL,35721,67570,101555,65804,66529,66131,2.324,White,White,Italiano/other...,Italiano/other...
10,GA,14105,31195,62185,44634,37509,37113,2.298,White,White,Italiano/other...,Italiano/other...
11,HI,2728,6861,8141,5025,5438,5708,2.357,Hawaiian,Hawaiian,Italiano/other...,Italiano/other...
12,IA,12318,16850,20552,12578,15456,15080,2.432,White,White,Italiano/other...,Italiano/other...
13,ID,3353,6754,7617,6116,5871,5893,2.439,White,White,Italiano/other...,Italiano/other...
14,IL,54274,82399,109431,67318,76938,75949,2.350,White,White,Italiano/other...,Italiano/other...
15,IN,17700,35039,45554,29408,31038,31229,2.363,White,White,Italiano/other...,Italiano/other...
16,KS,9439,15872,18728,12359,13966,13746,2.366,White,White,Italiano/other...,Italiano/other...
17,KY,14359,21149,25976,17372,19535,19192,2.344,White,White,Italiano/other...,Italiano/other...
18,LA,21035,35766,37086,21762,28713,28151,2.265,White,White,Italiano/other...,Italiano/other...
19,MA,16547,36487,58530,39061,36887,36410,2.408,White,White,Italiano/other...,Italiano/other...
20,MD,12803,26584,40107,27492,26122,26119,2.339,White,White,Italiano/other...,Italiano/other...
21,ME,4506,6193,8076,4632,5784,5740,2.435,White,White,Italiano/other...,Italiano/other...
22,MI,44665,62224,81500,47664,58288,57173,2.346,White,White,Italiano/other...,Italiano/other...
23,MN,14967,28263,37706,25120,25919,25775,2.424,White,White,Italiano/other...,Italiano/other...
24,MO,25039,34825,45850,28357,32753,32995,2.322,White,White,Italiano/other...,Italiano/other...
25,MS,9387,19577,21223,13200,15730,15554,2.281,White,White,Italiano/other...,Italiano/other...
26,MT,3678,5196,5052,3493,4328,4267,2.428,White,White,Italiano/other...,Italiano/other...
27,NC,22560,39162,58243,40127,39352,39175,2.284,White,White,Italiano/other...,Italiano/other...
28,ND,1821,4373,5784,3242,3776,3625,2.397,White,White,Italiano/other...,Italiano/other...
29,NE,7277,12034,15101,9573,10710,10614,2.361,White,White,Italiano/other...,Italiano/other...
30,NH,3699,6174,7534,4925,5614,5366,2.487,White,White,Italiano/other...,Italiano/other...
31,NJ,18583,43139,73119,48455,44384,44599,2.365,White,White,Italiano/other...,Italiano/other...
32,NM,2880,7833,11259,6312,6972,6992,2.357,White,White,Italiano/other...,Italiano/other...
33,NV,2598,6386,12585,9980,7707,7748,2.306,White,White,Italiano/other...,Italiano/other...
34,NY,69364,117076,167542,99497,111583,109968,2.371,White,White,Italiano/other...,Italiano/other...
35,OH,38654,71705,92355,55657,63514,62471,2.358,White,White,Italiano/other...,Italiano/other...
36,OK,11305,21504,22225,13831,17085,16823,2.356,White,White,Italiano/other...,Italiano/other...
37,OR,10466,18117,23200,14763,16373,16312,2.441,White,White,Italiano/other...,Italiano/other...
38,PA,28736,71515,90686,51544,59655,58848,2.355,White,White,Italiano/other...,Italiano/other...
39,RI,4148,5959,9093,6028,6181,6120,2.356,White,White,Italiano/other...,Italiano/other...
40,SC,14136,21814,27763,17073,20091,19669,2.292,White,White,Italiano/other...,Italiano/other...
41,SD,1897,5042,6175,3930,4181,4185,2.396,White,White,Italiano/other...,Italiano/other...
42,TN,18556,31035,43236,28085,29623,29762,2.260,White,White,Italiano/other...,Italiano/other...
43,TX,58549,124826,160076,109302,111357,110908,2.334,White,White,Italiano/other...,Italiano/other...
44,UT,7307,16772,20597,14146,14676,14126,2.371,White,White,Italiano/other...,Italiano/other...
45,VA,18236,35158,49755,33618,33623,33630,2.341,White,White,Italiano/other...,Italiano/other...
46,VT,2081,3163,3612,1958,2729,2612,2.381,White,White,Italiano/other...,Italiano/other...
47,WA,11431,29364,37868,23735,25193,25165,2.455,White,White,Italiano/other...,Italiano/other...
48,WI,18640,31430,36660,21630,26705,26456,2.425,White,White,Italiano/other...,Italiano/other...
49,WV,6873,10023,10711,6245,8479,8203,2.323,White,White,Italiano/other...,Italiano/other...
50,WY,1306,3064,2412,1296,1979,2040,2.465,White,White,Italiano/other...,Italiano/other...

In [75]:
%%time
pruebaconcat = pd.concat([df_nacimientos, dfu], axis=1)
pruebaconcat

CPU times: user 1.15 ms, sys: 160 Âµs, total: 1.31 ms
Wall time: 1.22 ms

,estado,B70,B80,B90,B00,Male,Female,Weight,estado,raza,raza_1,raza_2,raza_3
0,AK,1529,4529,4971,2714,3391,3396,2.464,AK,White,White,Italiano/other...,Italiano/other...
1,AL,14866,26254,33540,21033,23479,23407,2.277,AL,White,White,Italiano/other...,Italiano/other...
2,AR,5703,14453,16504,10678,11598,11751,2.318,AR,White,White,Italiano/other...,Italiano/other...
3,AZ,6523,17201,36109,25765,20775,20761,2.346,AZ,White,White,Italiano/other...,Italiano/other...
4,CA,56624,147762,274371,159740,156282,157163,2.405,CA,White,White,Italiano/other...,Italiano/other...
5,CO,12704,23079,32601,22479,22324,22024,2.292,CO,White,White,Italiano/other...,Italiano/other...
6,CT,6887,19684,30100,18537,18463,18173,2.384,CT,White,White,Italiano/other...,Italiano/other...
7,DC,4105,7863,12071,6088,7373,7232,2.258,DC,Black,Black,Italiano/other...,Italiano/other...
8,DE,1517,3398,7047,4769,4082,4052,2.302,DE,White,White,Italiano/other...,Italiano/other...
9,FL,35721,67570,101555,65804,66529,66131,2.324,FL,White,White,Italiano/other...,Italiano/other...
10,GA,14105,31195,62185,44634,37509,37113,2.298,GA,White,White,Italiano/other...,Italiano/other...
11,HI,2728,6861,8141,5025,5438,5708,2.357,HI,Hawaiian,Hawaiian,Italiano/other...,Italiano/other...
12,IA,12318,16850,20552,12578,15456,15080,2.432,IA,White,White,Italiano/other...,Italiano/other...
13,ID,3353,6754,7617,6116,5871,5893,2.439,ID,White,White,Italiano/other...,Italiano/other...
14,IL,54274,82399,109431,67318,76938,75949,2.350,IL,White,White,Italiano/other...,Italiano/other...
15,IN,17700,35039,45554,29408,31038,31229,2.363,IN,White,White,Italiano/other...,Italiano/other...
16,KS,9439,15872,18728,12359,13966,13746,2.366,KS,White,White,Italiano/other...,Italiano/other...
17,KY,14359,21149,25976,17372,19535,19192,2.344,KY,White,White,Italiano/other...,Italiano/other...
18,LA,21035,35766,37086,21762,28713,28151,2.265,LA,White,White,Italiano/other...,Italiano/other...
19,MA,16547,36487,58530,39061,36887,36410,2.408,MA,White,White,Italiano/other...,Italiano/other...
20,MD,12803,26584,40107,27492,26122,26119,2.339,MD,White,White,Italiano/other...,Italiano/other...
21,ME,4506,6193,8076,4632,5784,5740,2.435,ME,White,White,Italiano/other...,Italiano/other...
22,MI,44665,62224,81500,47664,58288,57173,2.346,MI,White,White,Italiano/other...,Italiano/other...
23,MN,14967,28263,37706,25120,25919,25775,2.424,MN,White,White,Italiano/other...,Italiano/other...
24,MO,25039,34825,45850,28357,32753,32995,2.322,MO,White,White,Italiano/other...,Italiano/other...
25,MS,9387,19577,21223,13200,15730,15554,2.281,MS,White,White,Italiano/other...,Italiano/other...
26,MT,3678,5196,5052,3493,4328,4267,2.428,MT,White,White,Italiano/other...,Italiano/other...
27,NC,22560,39162,58243,40127,39352,39175,2.284,NC,White,White,Italiano/other...,Italiano/other...
28,ND,1821,4373,5784,3242,3776,3625,2.397,ND,White,White,Italiano/other...,Italiano/other...
29,NE,7277,12034,15101,9573,10710,10614,2.361,NE,White,White,Italiano/other...,Italiano/other...
30,NH,3699,6174,7534,4925,5614,5366,2.487,NH,White,White,Italiano/other...,Italiano/other...
31,NJ,18583,43139,73119,48455,44384,44599,2.365,NJ,White,White,Italiano/other...,Italiano/other...
32,NM,2880,7833,11259,6312,6972,6992,2.357,NM,White,White,Italiano/other...,Italiano/other...
33,NV,2598,6386,12585,9980,7707,7748,2.306,NV,White,White,Italiano/other...,Italiano/other...
34,NY,69364,117076,167542,99497,111583,109968,2.371,NY,White,White,Italiano/other...,Italiano/other...
35,OH,38654,71705,92355,55657,63514,62471,2.358,OH,White,White,Italiano/other...,Italiano/other...
36,OK,11305,21504,22225,13831,17085,16823,2.356,OK,White,White,Italiano/other...,Italiano/other...
37,OR,10466,18117,23200,14763,16373,16312,2.441,OR,White,White,Italiano/other...,Italiano/other...
38,PA,28736,71515,90686,51544,59655,58848,2.355,PA,White,White,Italiano/other...,Italiano/other...
39,RI,4148,5959,9093,6028,6181,6120,2.356,RI,White,White,Italiano/other...,Italiano/other...
40,SC,14136,21814,27763,17073,20091,19669,2.292,SC,White,White,Italiano/other...,Italiano/other...
41,SD,1897,5042,6175,3930,4181,4185,2.396,SD,White,White,Italiano/other...,Italiano/other...
42,TN,18556,31035,43236,28085,29623,29762,2.260,TN,White,White,Italiano/other...,Italiano/other...
43,TX,58549,124826,160076,109302,111357,110908,2.334,TX,White,White,Italiano/other...,Italiano/other...
44,UT,7307,16772,20597,14146,14676,14126,2.371,UT,White,White,Italiano/other...,Italiano/other...
45,VA,18236,35158,49755,33618,33623,33630,2.341,VA,White,White,Italiano/other...,Italiano/other...
46,VT,2081,3163,3612,1958,2729,2612,2.381,VT,White,White,Italiano/other...,Italiano/other...
47,WA,11431,29364,37868,23735,25193,25165,2.455,WA,White,White,Italiano/other...,Italiano/other...
48,WI,18640,31430,36660,21630,26705,26456,2.425,WI,White,White,Italiano/other...,Italiano/other...
49,WV,6873,10023,10711,6245,8479,8203,2.323,WV,White,White,Italiano/other...,Italiano/other...
50,WY,1306,3064,2412,1296,1979,2040,2.465,WY,White,White,Italiano/other...,Italiano/other...

In [81]:
!pip install gcsfs

Collecting gcsfs
  Downloading gcsfs-0.7.1-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: google-auth>=1.2 in /opt/anaconda3/lib/python3.7/site-packages (from gcsfs) (1.24.0)
Collecting fsspec>=0.8.0
  Downloading fsspec-0.8.5-py3-none-any.whl (98 kB)
     |ââââââââââââââââââââââââââââââââ| 98 kB 2.0 MB/s eta 0:00:01
Collecting aiohttp
  Downloading aiohttp-3.7.3.tar.gz (1.1 MB)
     |ââââââââââââââââââââââââââââââââ| 1.1 MB 3.1 MB/s eta 0:00:01     |ââââââââââ                      | 337 kB 3.1 MB/s eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.7/site-packages (from gcsfs) (2.22.0)
Collecting google-auth-oauthlib
  Downloading google_auth_oauthlib-0.4.2-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: decorator in /opt/anaconda3/lib/python3.7/site-packages (from gcsfs) (4.4.1)
Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3.6" in /opt/anaconda3/lib/python3.7/site-packages (from google-auth>=1.2->gcsfs) (4.7)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/anaconda3/lib/python3.7/site-packages (from google-auth>=1.2->gcsfs) (0.2.8)
Requirement already satisfied: six>=1.9.0 in /opt/anaconda3/lib/python3.7/site-packages (from google-auth>=1.2->gcsfs) (1.14.0)
Requirement already satisfied: setuptools>=40.3.0 in /opt/anaconda3/lib/python3.7/site-packages (from google-auth>=1.2->gcsfs) (46.0.0.post20200309)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /opt/anaconda3/lib/python3.7/site-packages (from google-auth>=1.2->gcsfs) (4.2.1)
Collecting multidict<7.0,>=4.5
  Downloading multidict-5.1.0.tar.gz (53 kB)
     |ââââââââââââââââââââââââââââââââ| 53 kB 2.1 MB/s eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting async-timeout<4.0,>=3.0
  Downloading async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting typing-extensions>=3.6.5
  Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Requirement already satisfied: chardet<4.0,>=2.0 in /opt/anaconda3/lib/python3.7/site-packages (from aiohttp->gcsfs) (3.0.4)
Requirement already satisfied: attrs>=17.3.0 in /opt/anaconda3/lib/python3.7/site-packages (from aiohttp->gcsfs) (19.3.0)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.6.3.tar.gz (176 kB)
     |ââââââââââââââââââââââââââââââââ| 176 kB 2.4 MB/s eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.7/site-packages (from requests->gcsfs) (2019.11.28)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/anaconda3/lib/python3.7/site-packages (from requests->gcsfs) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in /opt/anaconda3/lib/python3.7/site-packages (from requests->gcsfs) (2.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /opt/anaconda3/lib/python3.7/site-packages (from google-auth-oauthlib->gcsfs) (1.3.0)
Requirement already satisfied: pyasn1>=0.1.3 in /opt/anaconda3/lib/python3.7/site-packages (from rsa<5,>=3.1.4; python_version >= "3.6"->google-auth>=1.2->gcsfs) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /opt/anaconda3/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib->gcsfs) (3.1.0)
Building wheels for collected packages: aiohttp, multidict, yarl
  Building wheel for aiohttp (PEP 517) ... done
  Created wheel for aiohttp: filename=aiohttp-3.7.3-cp37-cp37m-macosx_10_9_x86_64.whl size=647203 sha256=a8161a71f22cd6a59c0034bce6ef585fabba424160e30bffd1acdc92cef0540f
  Stored in directory: /Users/victoriasofia93/Library/Caches/pip/wheels/c7/04/a7/8658c1367ef598e2736aa1eff1a3dba32fc4c8bdec8db0e989
  Building wheel for multidict (PEP 517) ... done
  Created wheel for multidict: filename=multidict-5.1.0-cp37-cp37m-macosx_10_9_x86_64.whl size=48972 sha256=cba7338cf86d65559b1cffd316a9404feecd0045312a07d77cc1fc11bf563628
  Stored in directory: /Users/victoriasofia93/Library/Caches/pip/wheels/da/2b/ba/2e1aff64d848461c1c0b882f2f3576d0b56ab17735672b84f6
  Building wheel for yarl (PEP 517) ... done
  Created wheel for yarl: filename=yarl-1.6.3-cp37-cp37m-macosx_10_9_x86_64.whl size=125262 sha256=bffe5582c775fd7bbfc4ad38e76e500ad6e4748c2c83db32fe4f87800f5824c8
  Stored in directory: /Users/victoriasofia93/Library/Caches/pip/wheels/3d/52/7d/31f09641099ee338d33dc146d9bd6d789fc7557a8bee9c5ff7
Successfully built aiohttp multidict yarl
Installing collected packages: fsspec, multidict, async-timeout, typing-extensions, yarl, aiohttp, google-auth-oauthlib, gcsfs
  Attempting uninstall: fsspec
    Found existing installation: fsspec 0.6.2
    Uninstalling fsspec-0.6.2:
      Successfully uninstalled fsspec-0.6.2
Successfully installed aiohttp-3.7.3 async-timeout-3.0.1 fsspec-0.8.5 gcsfs-0.7.1 google-auth-oauthlib-0.4.2 multidict-5.1.0 typing-extensions-3.7.4.3 yarl-1.6.3